### GET / WEBSITE
GET http://localhost:3000

### get dashboard
GET http://localhost:3000/dashboard


### data endpoint
GET http://localhost:3000/api/data

### POST user

POST http://localhost:3000/api/data
Content-Type: application/json

{
    "name": "Dieguito"
}

### DELETE user
DELETE http://localhost:3000/api/data/