### GET Website
GET http://localhost:3000/


###register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "john_doe",
    "password": "password123"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "john_doe",
    "password": "password123"
}

### FETCH TODOS
GET http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1NDY5ODU0LCJleHAiOjE3NzU1NTYyNTR9.qYlSuXLtK5NjLfQNBEk2TdYzOXcvE1lPzouSRRktZg0

### CREATE TODO
POST http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1NDY5ODU0LCJleHAiOjE3NzU1NTYyNTR9.qYlSuXLtK5NjLfQNBEk2TdYzOXcvE1lPzouSRRktZg0
Content-Type: application/json

{
    "task": "Buy groceries"
}

### UPDATE TODO
PUT http://localhost:3000/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1NDY5ODU0LCJleHAiOjE3NzU1NTYyNTR9.qYlSuXLtK5NjLfQNBEk2TdYzOXcvE1lPzouSRRktZg0
Content-Type: application/json

{
    "completed": 1
}

### DELETE TODO
DELETE http://localhost:3000/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzc1NDY5ODU0LCJleHAiOjE3NzU1NTYyNTR9.qYlSuXLtK5NjLfQNBEk2TdYzOXcvE1lPzouSRRktZg0